# Generated by Django 5.0.4 on 2024-05-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenGato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'gatito',
                'verbose_name_plural': 'gatitos',
            },
        ),
    ]
