# Generated by Django 5.0.4 on 2024-05-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagengato',
            name='sexo',
            field=models.IntegerField(choices=[(0, 'Macho'), (1, 'Hembra')], null=True),
        ),
    ]
