# Generated by Django 5.0.4 on 2024-05-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagengato_sexo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenGato',
        ),
    ]
