# Generated by Django 5.0.4 on 2024-05-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevocliente',
            name='DNI',
            field=models.IntegerField(unique=True),
        ),
    ]
