# Generated by Django 5.0.4 on 2024-05-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_nuevocliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='localidad',
            field=models.CharField(error_messages={'unique': 'Esa ciudad ya existe en el sistema.'}, max_length=100, unique=True),
        ),
    ]
