# Generated by Django 5.0.4 on 2024-05-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_nuevocliente_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(error_messages={'unique': 'Ese pais ya existe en el sistema.'}, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Paises',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='NuevoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Ese producto ya esta registrado.'}, max_length=100, unique=True)),
                ('precio', models.IntegerField()),
                ('pais_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.pais')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
