# Generated by Django 5.0.4 on 2024-05-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.pais'),
        ),
    ]
