# Generated by Django 5.0.4 on 2024-05-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_localidad_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevoproducto',
            name='pais_origen',
        ),
    ]
