# Generated by Django 5.0.4 on 2024-05-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_remove_nuevoproducto_pais_origen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuevocliente',
            old_name='DNI',
            new_name='dni',
        ),
    ]
