# Generated by Django 5.0.4 on 2024-05-14 22:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0004_alter_usuario_fecha_ingreso'),
        ('ventas', '0010_rename_dni_nuevocliente_dni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Esa marca ya esta registrada.'}, max_length=100, unique=True, verbose_name='Nombre de la marca'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='pais_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.pais', verbose_name='País de origen'),
        ),
        migrations.AlterField(
            model_name='nuevocliente',
            name='dni',
            field=models.CharField(error_messages={'unique': 'El DNI debe ir sin puntos'}, max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'Ingrese un máximo de 8 dígitos.')], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='nuevoproducto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.marca', verbose_name='Marca del producto'),
        ),
        migrations.AlterField(
            model_name='nuevoproducto',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ese producto ya esta registrado.'}, max_length=100, unique=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='pais',
            field=models.CharField(error_messages={'unique': 'Ese pais ya existe en el sistema.'}, max_length=100, unique=True, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.nuevocliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.nuevoproducto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso.usuario'),
        ),
    ]
