# Generated by Django 5.0.4 on 2024-05-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0002_usuario_alter_ingreso_options_alter_ingreso_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingreso.usuario', verbose_name='Entrada de usuario'),
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egreso', models.DateTimeField(auto_now_add=True, verbose_name='Hora de salida')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingreso.usuario', verbose_name='Salida de usuario')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
            },
        ),
    ]
