# Generated by Django 5.0.4 on 2024-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0003_alter_ingreso_usuario_egreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Ingreso a la empresa'),
        ),
    ]
